# SPDX-FileCopyrightText: 2022 Kattni Rembor
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Check REUSE

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install pre-commit
      run: |
        pip install pre-commit
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
